codecov:
  branch: master
  max_report_age: off

# Documentation for this at https://docs.codecov.io/docs/commit-status
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.5%