job_config: &job_config
  working_directory: ~/workspace
  docker:
    - image: cimg/openjdk:16.0-browsers

version: 2.1
jobs:
  code style:
    <<: *job_config
    steps:
      - checkout

      - restore_cache:
          keys:
            - codestyle-{{ checksum "buildSrc/src/main/kotlin/Deps.kt" }}

      - run:
          name: Perform code style check
          command: ./gradlew ktlint

#      - run:
#          name: Commit code style changes
#          command: scripts/git-commit-if-changes.sh "code style"

      - save_cache:
          paths:
            - ~/.gradle
            - ~/.konan
          key: codestyle-{{ checksum "buildSrc/src/main/kotlin/Deps.kt" }}

  build:
    <<: *job_config
    steps:
      - checkout

      - restore_cache:
          keys:
            - build-{{ checksum "buildSrc/src/main/kotlin/Deps.kt" }}

      - run: ./gradlew :kotlin-html-writer:assemble :kotlin-html-ktor:assemble --stacktrace

      - save_cache:
          paths:
            - ~/.gradle
            - ~/.konan
          key: build-{{ checksum "buildSrc/src/main/kotlin/Deps.kt" }}

  unit test:
    <<: *job_config
    steps:
      - checkout

      - restore_cache:
          keys:
            - unittest-{{ checksum "buildSrc/src/main/kotlin/Deps.kt" }}

      - run:
          name: Run Tests
          command: ./gradlew :kotlin-html-writer:jvmTest :kotlin-html-writer:jsTest :kotlin-html-writer:jvmCodeCoverageReport --stacktrace

      - run:
          name: Upload to CodeCov
          command: bash <(curl -s https://codecov.io/bash) -f ./build/jacoco/*.xml

      - save_cache:
          paths:
            - ~/.gradle
            - ~/.konan
          key: unittest-{{ checksum "buildSrc/src/main/kotlin/Deps.kt" }}

  upload:
    <<: *job_config
    environment:
      GRADLE_OPTS: -Xmx1536m
    steps:
      - checkout

      - restore_cache:
          keys:
            - upload-{{ checksum "buildSrc/src/main/kotlin/Deps.kt" }}

      - run:
          name: Upload kotlin-html-writer to Bintray
          command: ./gradlew :kotlin-html-writer:publishAllPublicationsToBintrayRepository

      - run:
          name: Upload kotlin-html-style-builder to Bintray
          command: ./gradlew :kotlin-html-style-builder:publishAllPublicationsToBintrayRepository

      - run:
          name: Upload kotlin-html-style-builder-desktop to Bintray
          command: ./gradlew :kotlin-html-style-builder-desktop:publishAllPublicationsToBintrayRepository

      - run:
          name: Upload kotlin-html-style-builder-phone to Bintray
          command: ./gradlew :kotlin-html-style-builder-phone:publishAllPublicationsToBintrayRepository

      - run:
          name: Upload kotlin-html-style-builder-tablet to Bintray
          command: ./gradlew :kotlin-html-style-builder-tablet:publishAllPublicationsToBintrayRepository

      - run:
          name: Upload kotlin-html-ktor to Bintray and Publish
          command: ./gradlew :kotlin-html-ktor:bintrayUpload

#      - run:
#          name: Checkout Master
#          command: git checkout main
#
#      - run:
#          name: Configure GIT
#          command: |
#            git config user.email "circleci@circleci.com"
#            git config user.name "CircleCI"
#            git fetch origin
#            git pull
#            git push --set-upstream origin master
#
#      - run:
#          name: Update version in documentation
#          command: ./gradlew updateVersionInDocumentation
#
#      - run:
#          name: Commit documentation changes
#          command: scripts/git-commit-if-changes.sh "version update for release"

      - save_cache:
          paths:
            - ~/.gradle
            - ~/.konan
          key: upload-{{ checksum "buildSrc/src/main/kotlin/Deps.kt" }}

workflows:
  version: 2
  Build and Check:
    jobs:
      - code style
      - build:
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
      - unit test:
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
      - upload:
          requires:
            - build
            - unit test
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              ignore: /.*/
