name: Build

on:
  pull_request:

jobs:
  code-style:
    name: Code Style
    runs-on: ubuntu-latest
    container:
      image: cimg/openjdk:11.0-browsers

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Kotlin Code Style
        run: ./gradlew ktlintFormat

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: code style

  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: cimg/openjdk:11.0-browsers

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: ./gradlew :kotlin-html-writer:assemble :kotlin-html-ktor:assemble --stacktrace

  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: markhobson/maven-chrome:jdk-17

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: ./gradlew :kotlin-html-writer:jvmTest :kotlin-html-writer:jsTest :kotlin-html-writer:jvmCodeCoverageReport --stacktrace
